drop index if exists M_idx;
create INDEX M_idx on M(FO, CR);
drop index if exists P_idx ;
create INDEX P_idx on P(PT, PTPR);
drop index if exists N_idx ;
create INDEX N_idx on N(A, PT, PR);
drop index if exists L ;
create INDEX L_idx on L(ET, RR);
drop index if exists L2_idx ;
create INDEX L2_idx on L(PR);
drop index if exists F_idx ;
create INDEX F_idx on F(O);
drop index if exists R_idx ;
create INDEX R_idx on R(RPR);
drop index if exists S_idx  ;
create INDEX S_idx  on S(ET, RR);
drop index if exists H_idx ;
create INDEX H_idx on H(HI, PT, PR );
drop index if exists C_idx ;
create INDEX C_idx on C(CR);
drop index if exists M2_idx ;
create INDEX M2_idx on M(CR);
