SELECT L0.PR,
  M.CR,
  N.PR,
  L1.RR,
  F.O,
  R.RPR,
  S.PR,
  H.PR,
  C0.CR,
  C1.CR,
  C2.CR
FROM L L0
INNER JOIN M
ON M.CR = L0.IPR
LEFT OUTER JOIN F
ON F.O = M.FO
LEFT OUTER JOIN R
ON R.RPR = L0.RR
LEFT OUTER JOIN S
ON (S.ET = 2)
AND (S.RR  = L0.RR)
LEFT OUTER JOIN P
ON (P.PT       = 3)
AND (P.PTPR = L0.PR)
LEFT OUTER JOIN N
ON (N.A         = 1)
AND ((N.PT = 3)
AND (N.PR   = L0.PR))
LEFT OUTER JOIN L L1
ON (L1.ET = 2)
AND (L1.RR  = L0.RR)
LEFT OUTER JOIN H
ON (H.HI     = 1)
AND ((H.PT = 3)
AND (H.PR   = L0.PR))
LEFT OUTER JOIN C C0
ON C0.CR = L0.CR
LEFT OUTER JOIN C C1
ON C1.CR = C0.UPR
LEFT OUTER JOIN C C2
ON C2.CR = C0.FPR ;
